---
- hosts: localhost
  gather_facts: no
  ignore_unreachable: yes
  vars:
    cml_servers: "{{ cml_server_list }}"                          # From POST
    colab_email: "{{ colab_user_email }}"                         # From POST
    colab_username: "{{ colab_user_username }}"                   # From POST
    vcenter_address: "{{ vcenter_address }}"                      # From POST
    cml_admin_account: "{{ cml_account }}"                        # From Vault
    cml_admin_password: "{{ cml_password }}"                      # From Vault
    aws_access_key: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"     # From Vault
    aws_secret_key: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}" # From Vault
    aws_access_key_prod: "{{ aws_prod_key_vault }}"               # From Vault
    aws_secret_key_prod: "{{ aws_prod_token_vault }}"             # From Vault
    aws_region_prod: "{{ aws_prod_region_vault }}"                # From Vault
    colabot_cipher: "{{ cipher_vault }}"                          # From Vault
    iam_group: "{{ aws_iam_group_vault }}"                        # From Vault
    wxt_bearer: "{{ wxt_bearer_vault }}"                          # From Vault
    vcenter_user_group: "{{ vcenter_sso_group_vault }}"           # From Vault
    vcenter_admin_username: "{{ vcenter_admin_account_vault }}"   # From Vault
    vcenter_admin_password: "{{ vcenter_admin_password_vault }}"  # From Vault
    meraki_key: "{{ meraki_auth_vault }}"                         # From Vault
    networkId: "{{ meraki_netid_vault }}"                         # From Vault
    cml_results: []
    check_flag: false
    successful_aws_creation: false
    api_cml_authenticate: '/api/v0/authenticate'
    api_cml_create_account: '/api/v0/users/'
    message: ''
    meraki_account_id: ""
  tasks:
  - name: Get IAM user info
    amazon.aws.iam_user_info:
      group: "{{ iam_group }}"
    register: results
  - name: Save users to a list
    set_fact:
      colabot_user_list: "{{ results.iam_users }}"
  - name: List MFA devices
    community.aws.iam_mfa_device_info:
      user_name: "{{ item.user_name }}"
    register: mfa_devices    
    with_items: "{{ colabot_user_list }}"
  - name: Save mfa devices to a list
    set_fact:
      mfa_devices_list: "{{ mfa_devices.results }}"
  # - debug: 
  #     msg:
  #       - "{{ item.mfa_devices }}"
  #   with_items: "{{ mfa_devices_list }}"
  - name: Debug user info if MFA devices list is empty
    debug: 
      msg: "{{ item }}"
    loop: "{{ mfa_devices_list }}"
    when: item == "[]"