---
- name: AWS Create User
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
  - name: Create new IAM user
    iam:
      iam_type: user
      name: "{{ausername}}"
      state: present
      aws_access_key: "{{lookup('env','AWS_ACCESS_KEY_ID')}}"
      aws_secret_key: "{{lookup('env','AWS_SECRET_ACCESS_KEY')}}"
      password: "{{apassword}}"
      access_key_state: create
      groups: "{{igroup}}"
    register: iam_user

  - debug: var=iam_user