---
- name: AWS Create User
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
  - name: Create new IAM user
    iam:
      iam_type: user
      name: "{{ aws_username }}"
      state: present
#      aws_access_key: "{{lookup('env','ACCESS_KEY')}}"
#      aws_secret_key: "{{lookup('env','ACCESS_SECRET_KEY')}}"
      password: "{{ aws_password }}"
      access_key_state: create
      groups: "{{ iam_group }}"
    register: iam_user

  - debug: var=iam_user