---
- hosts: login
  gather_facts: no
  connection: ssh
  vars:
    message: ''
  tasks:
    - name: Add user to remote server
      user:
        name: "{{ username }}"
        password: "{{ password | password_hash('sha512', 'mysecretsalt')}}"
        update_password: always
        groups: docker
        shell: /bin/bash
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa
      ignore_errors: true
      register: login_server_user
    - name: Create Success message for Login Server
      set_fact:
        message: "{{ message + ' - ' + inventory_hostname + ' Account Created! \n' }}"
      when: login_server_user.changed == true and login_server_user.failed == false
    - name: Create Fail message for Login Server
      set_fact:
        message: "{{ message + ' - ' + inventory_hostname + ' Account Creation Failed! \n' }}"
      when: login_server_user.failed == true
      ignore_errors: true
