---
- hosts: login
  gather_facts: no
  connection: ssh
  tasks:
    - name: Add user to remote server
      user:
        name: "{{ username }}"
        password: "{{ password | password_hash('sha512', 'mysecretsalt')}}"
        update_password: always
        groups: docker
        shell: /bin/bash
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa
    - name: Get hostname
      debug: msg="{{ inventory_hostname }}"
