---
- hosts: login
  gather_facts: no
  connection: ssh
  vars:
    message: ''
  tasks:
    - name: Remove user
      user:
        name: "{{ username }}"
        state: absent
        remove: yes
      ignore_errors: true
      register: login_server_user
    - name: Delete Success message for Login Server
      set_fact:
        message: "{{ message + ' - ' + inventory_hostname + ' Account Deleted! \n' }}"
      when: login_server_user.changed == true and login_server_user.failed == false
    - name: Delete Fail message for Login Server
      set_fact:
        message: "{{ message + ' - ' + inventory_hostname + ' Account Deletion Failed! \n' }}"
      when: login_server_user.failed == true
      ignore_errors: true
    - name: Get message
      debug: msg="{{ message }}"