- hosts: localhost
  vars:
    username: "{{ colab_user_username }}"                         # From POST
    kubeconfig: "{{ kubeconfig_from_vault }}"                     # From Vault
    webext_bearer: "{{ wxt_bearer_vault }}"                       # From Vault
    colab_email: "{{ colab_user_email }}"                         # From POST
    cert_target: "{{ cert_post_target | default('prod') }}"       # From POST
    subdomain: workshops.colab.ciscops.net
    helm_url: https://get.helm.sh/helm-v3.4.0-linux-amd64.tar.gz
    helm_tar: helm-v3.4.0-linux-amd64.tar.gz

  tasks:
    - name: Fail on missing vars
      fail: msg="'username' is not defined"
      when: username is undefined
    - fail: msg="'kubeconfig' is not defined"
      when: kubeconfig is undefined

    - name: Create temporary directory
      tempfile:
        suffix: helm
        state: directory
      register: tempdir_var

    - name: Set tempdir
      set_fact:
        tempdir: "{{ tempdir_var.path }}"

    - name: Set helm_binary and kubeconfig
      set_fact:
        helm_binary: "{{ tempdir }}/linux-amd64/helm"
        kubeconfig_file: "{{ tempdir }}/kubeconfig"

    - name: Download helm binary
      get_url:
        url: "{{ helm_url }}"
        dest: "{{ tempdir }}"
      ignore_errors: true

    - name: Unpack helm binary
      unarchive:
        src: "{{ tempdir }}/{{ helm_tar }}"
        dest: "{{ tempdir }}"
      ignore_errors: true

    - name: Create kubeconfig
      template:
        src: kubeconfig.j2
        dest: "{{ kubeconfig_file }}"
      ignore_errors: true

    - name: Add stable chart repo
      community.kubernetes.helm_repository:
        binary_path: "{{ helm_binary }}"
        name: gitlab
        repo_url: "https://charts.gitlab.io/"
      ignore_errors: true

    - name: Install helm chart
      community.kubernetes.helm:
        binary_path: "{{ helm_binary }}"
        kubeconfig: "{{ kubeconfig_file }}"
        chart_ref: gitlab/gitlab
        chart_version: 4.5.3
        update_repo_cache: yes
        namespace: default
        state: present
        release_name: "gitlab-{{ username }}"
        release_values:
          image:
            repository: registry.gitlab.com/gitlab-org/build/cng/gitlab-webservice-ce
          workhorse:
            image: registry.gitlab.com/gitlab-org/build/cng/gitlab-workhorse-ce
          gitlab:
            webservice:
              ingress:
                tls:
                  enabled: true
                  secretName: "{{ username }}-gitlab-tls"
          registry:
            ingress:
              tls:
                secretName: "{{ username }}-registry-tls"
          minio:
            ingress:
              tls:
                secretName: "{{ username }}-minio-tls"

          global:
            hosts:
              domain: "{{ username }}.{{ subdomain }}"
            ingress:
              annotations:
                kubernetes.io/ingress.class: workshops
                cert-manager.io/issuer: "letsencrypt-{{ cert_target }}"
              configureCertmanager: false
              tls:
                enabled: true
            grafana:
              enabled: false
          certmanager:
            install: false
          prometheus:
            install: false
          nginx-ingress:
            enabled: false
      ignore_errors: true
      register: helm_results

    - name: Fetch password
      community.kubernetes.k8s_info:
        kubeconfig: "{{ kubeconfig_file }}"
        api_version: v1
        kind: Secret
        namespace: default
        name: "gitlab-{{ username }}-gitlab-initial-root-password"
      register: password_var

    - name: Remove temp directory
      file:
        path: "{{ tempdir }}"
        state: absent

    - name: set password variable
      set_fact:
        gitlab_password: "{{ password_var.resources[0].data.password | b64decode }}"

    - name: Create Success message
      set_fact:
        message: "Your GitLab host will be gitlab.{{ username }}.{{ subdomain }}\n - Username: root\n - Password: {{ gitlab_password }}\n"
        check_flag: true
      ignore_errors: true
      when: helm_results.failed == false

    - name: Create Failed message
      set_fact:
        message: "Deployment Failed"
        check_flag: true
      ignore_errors: true
      when: helm_results.failed == true

    - name: Send WxT Message
      uri:
        url: "https://api.ciscospark.com/v1/messages"
        method: POST
        return_content: yes
        body: "{{ {'toPersonEmail': colab_email, 'markdown': message } | to_json }}"
        validate_certs: no
        headers: "{{ {
        'Content-Type': 'application/json',
        'Authorization': 'Bearer ' + webext_bearer } }}"