---
- hosts: localhost
  gather_facts: no
  vars:
    aws_access_key_prod: "{{ aws_prod_key_vault }}"               # From Vault
    aws_secret_key_prod: "{{ aws_prod_token_vault }}"             # From Vault
    aws_region_prod: "{{ aws_prod_region_vault }}"                # From Vault
    username: "{{ colab_user_username }}"                         # From POST
    colab_email: "{{ colab_user_email }}"                         # From POST
    wxt_bearer: "{{ wxt_bearer_vault }}"                          # From Vault
  tasks:
  - name: get gitlab record
    dynamo_gitlab:
      action: "check_record"
      aws_key: "{{ aws_access_key_prod }}"
      aws_secret: "{{ aws_secret_key_prod }}"
      aws_region: "{{ aws_prod_region_vault }}"
      dynamo_table: colab_gitlab
      colab_username: "{{ username }}"
    register: record_results
    ignore_errors: true
  - name: Send No Account WxT Message
    uri:
      url: "https://api.ciscospark.com/v1/messages"
      method: POST
      return_content: yes
      body: "{{ {'toPersonEmail': colab_email, 'markdown': 'No GitLab account for ' + username } | to_json }}"
      validate_certs: no
      headers: "{{ {
        'Content-Type': 'application/json',
        'Authorization': 'Bearer ' + wxt_bearer } }}"
    when: record_results.get('meta') == false
  - name: Extend gitlab record
    dynamo_gitlab:
      action: "create"
      aws_key: "{{ aws_access_key_prod }}"
      aws_secret: "{{ aws_secret_key_prod }}"
      aws_region: "{{ aws_prod_region_vault }}"
      dynamo_table: colab_gitlab
      colab_username:  "{{ username }}"
    register: extend_result
    when: record_results.get('meta') == true
  - name: Send Extended Account WxT Message
    uri:
      url: "https://api.ciscospark.com/v1/messages"
      method: POST
      return_content: yes
      body: "{{ {'toPersonEmail': colab_email, 'markdown': 'Your GitLab deployment has been extended for 7 days' } | to_json }}"
      validate_certs: no
      headers: "{{ {
        'Content-Type': 'application/json',
        'Authorization': 'Bearer ' + wxt_bearer } }}"
    when: extend_result.get('meta') == 200
    ignore_errors: true
  - name: Send Extended Account Failed WxT Message
    uri:
      url: "https://api.ciscospark.com/v1/messages"
      method: POST
      return_content: yes
      body: "{{ {'toPersonEmail': colab_email, 'markdown': 'Error extending GitLab deployment' } | to_json }}"
      validate_certs: no
      headers: "{{ {
        'Content-Type': 'application/json',
        'Authorization': 'Bearer ' + wxt_bearer } }}"
    when: extend_result.get('failed') == true or record_results.get('failed') == true