- hosts: localhost
  vars:
    kubeconfig: "{{ kubeconfig_vault }}"                    # From Vault

    - name: Create temporary directory
      tempfile:
        suffix: helm
        state: directory
      register: tempdir_var

    - name: Set tempdir
      set_fact:
        tempdir: "{{ tempdir_var.path }}"

    - name: Set helm_binary and kubeconfig
      set_fact:
        kubeconfig_file: "{{ tempdir }}/kubeconfig"

    - name: print kubeconfig
      debug:
        var: kubeconfig

    - name: Create kubeconfig
      template:
        src: kubeconfig.j2
        dest: "{{ kubeconfig_file }}"

    - name: get me some vars
      include_vars:
        file: "{{ kubeconfig_file }}"
        name: my_var

    - name: print file kube
      debug:
        var: my_var

    - name: Remove temp directory
      file:
        path: "{{ tempdir }}"
        state: absent