- hosts: localhost
  vars:
    kubeconfig: "{{ kubeconfig_from_vault }}"                    # From Vault
    subdomain: workshops.colab.ciscops.net
    helm_url: https://get.helm.sh/helm-v3.4.0-linux-amd64.tar.gz
    helm_tar: helm-v3.4.0-linux-amd64.tar.gz
  tasks:
    - name: Create temporary directory
      tempfile:
        suffix: helm
        state: directory
      register: tempdir_var

    - name: Set tempdir
      set_fact:
        tempdir: "{{ tempdir_var.path }}"

    - name: Set helm_binary and kubeconfig
      set_fact:
        helm_binary: "{{ tempdir }}/linux-amd64/helm"
        kubeconfig_file: "{{ tempdir }}/kubeconfig"
    - name: Download helm binary
      get_url:
        url: "{{ helm_url }}"
        dest: "{{ tempdir }}"

    - name: Unpack helm binary
      unarchive:
        src: "{{ tempdir }}/{{ helm_tar }}"
        dest: "{{ tempdir }}"
    - name: print kubeconfig
      debug:
        var: kubeconfig

    - name: Create kubeconfig
      template:
        src: kubeconfig.j2
        dest: "{{ kubeconfig_file }}"

    - name: get me some vars
      include_vars:
        file: "{{ kubeconfig_file }}"
        name: my_var

    - name: print file kube
      debug:
        var: my_var

    - name: Remove temp directory
      file:
        path: "{{ tempdir }}"
        state: absent

    - name: print kubeconfig
      debug:
        var: kubeconfig